### ISSUE TITLE
Critical CSS editor delivers an error when trying to extract critical css

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-css-optimization#20]
When trying to extract the critical css for one of my websites, both with Firefox and Chrome, I get a popup stating

Error: Critical CSS <style> element not found.

**Comment by optimalisatie** [comment]
The issue has been fixed in the latest update.

https://github.com/o10n-x/wordpress-css-optimization/releases/tag/0.0.78

**Comment by AlphaDE** [comment]
The problem persists with the current version.

Error: Critical CSS <style> element not found.
